config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#delete'

  resources :posts, except: [:destroy] do
    resources :comments, only: [:create]
  end

  resources :users, only: [:create, :show, :edit, :update]
  resources :categories, except: [:delete, :edit, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories
  
  validates :name, presence: true, uniqueness: true, length: { minimum: 2 }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: { minimum: 5 }
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: { minimum: 3}
  has_secure_password validations: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "Must be logged in!"
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  before_action :require_user, except: [:index, :show]

 def index
   @categories = Category.all
 end

 def show

 end

 def new
   @category = Category.new
 end

 def create
   @category = Category.create(category_params)

   if @category.save
     flash[:notice] = "A new category has been added."
     redirect_to root_path
   else
     render :new
   end
 end

 private

 def category_params
   params.require(:category).permit(:name)
 end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comments_params)
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = "A new comment has been created."
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "You created a post!"
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update

    if @post.update(post_params)
      flash[:notice] = "This post has been updated!"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def require_same_user
    if @post.creator.username != current_user.username
      flash[:error] = "You aren't allowed to do that!"
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You've logged in!"
      redirect_to root_path
    else
      flash[:error] = "Either your username or password was incorrect"
      redirect_to login_path
    end

  end

  def delete
    session[:user_id] = nil
    flash[:notice] = "You've logged out!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]

  def show

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "You are registered!"
      session[:user_id] = @user.id
      flash[:notice] = "You've logged in!"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Profile has been updated."
      redirect_to user_path(@user)
    else
      render :edit
    end

  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:error] = "You aren't allowed to do that!"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(str)
    str.starts_with?("http://") ? str : "http://#{str}"
  end

  def time_format(time)
    time.strftime("%F %H:%M")
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category)%></span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'New Category'%>

<%= render 'shared/errors', object: @category %>

<div class="well">
  <%= form_for @category do |f|%>

    <div class="control-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="control-group">
      <%= f.submit 'Create Category', class: 'btn btn-success'%>
    </div>
  <%end%>
</div>

app/views/categories/show.html.erb
<% header = link_to('All Posts', posts_path) + " &raquo; #{@category.name}".html_safe%>

<%= render 'shared/content_title', title: header%>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<%end%>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>

  <li>
    <%= link_to 'New Post', new_post_path %>
  </li>

  <% if !logged_in?%>
    <li>
      <%= link_to 'Log in', login_path%>
    </li>

    <li>
      <%= link_to 'Register', register_path%>
    </li>
  <%end%>
</ul>

<div class="btn-group nav_item">
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    Categories <span class="caret"></span>
  <%end%>
  <ul class="dropdown-menu">
    <% Category.all.each do |category|%>
      <li><%= link_to category.name, category_path(category)%></li>
    <%end%>
    <li class="divider"></li>
    <li>
      <%if logged_in? %>
        <%= link_to (new_category_path) do%>
          <i class="icon-plus"></i>
          New Category
        <%end%>
      <%end%>
    </li>
  </ul>
</div>

<% if logged_in? %>
  <div class="btn-group nav_item">
    <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do%>
      Profile <span class="caret"></span>
    <%end%>
    <ul class="dropdown-menu">
      <li>
        <%= link_to user_path(current_user) do%>
          <i class="icon-user"></i>
          View Profile
        <%end%>
      </li>
      <li>
        <%= link_to edit_user_path(current_user) do%>
          <i class="icon-pencil"></i>
          Edit Profile
        <%end%>
      </li>
      <li>
        <%= link_to 'Log out', logout_path%>
      </li>
    </ul>
  </div>
<%end%>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_comments.html.erb
<% show_title ||= false%>
<% if show_title %>
  <p>Title: <%= link_to comment.post.title, post_path(comment.post) %></p>
<%end%>
<p class="comment-name"><%= comment.creator.username %>:</p>
<p class="quiet"> created at:  <%= time_format(comment.created_at)%></p>
<div class="well">
  <p><%= comment.body %></p>
</div>

app/views/posts/_form.html.erb
<%= render 'shared/errors', object: @post%>

<div class="well">
  <%= form_for @post do |p|%>

    <div class="control-group">
      <%= p.label :title %>
      <%= p.text_field :title %>
    </div>

    <div class="control-group">
      <%= p.label :url %>
      <%= p.text_field :url %>
    </div>

    <div class="control-group">
      <%= p.label :description %>
      <%= p.text_area :description %>
    </div>

    <div class="control-group">
      <%= p.collection_check_boxes :category_ids, Category.all, :id, :name do |checkbox|%>
        <% checkbox.label(class: 'checkbox inline') {checkbox.check_box(class: 'checkbox') + checkbox.text} %>
      <%end%>
    </div>

    <%= p.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>
  <%end%>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class="span8 well">
    <%= render post.categories %>
    <h4><%= link_to post.title, post_path(post) %></h4>
    <p><%= post.description%></p>
    <p>
      <span class="quiet">posted by: <%= post.creator.username %></span><br/>
      <span class="quiet">created at: <%= time_format(post.created_at)%></span>
    </p>
    <% if logged_in?  && current_user.username == post.creator.username%>
      <%= link_to 'edit', edit_post_path(post)%>
    <%end%>
    <p><%= link_to "comments #{post.comments.count}", post_path(post)%></p>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'form'%>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts'%>
<p class="lead">
  <h3>Welcome! Here are all the current posts!</h3>
</p>

<% @posts.each do |post|%>
  <%= render 'post', post: post %>
<%end%>

app/views/posts/new.html.erb
<h5>Create a post!<h5/>
<% if logged_in? %>
  <%= render 'form'%>
<%end%>

app/views/posts/show.html.erb
<% all_posts = link_to 'Posts', posts_path %>

<% if logged_in?  && current_user.username == @post.creator.username%>
  <p class="pull-right">
    [<%= link_to 'edit', edit_post_path(@post)%>]
  </p>
<%end%>

<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: "#{all_posts} &raquo; #{@post.title}".html_safe%>

<p>
    <%= @post.description%>
</p>
<hr/>

<div>
  <h5>Create a comment</h5>
  <% if logged_in? %>
    <%= render 'shared/errors', object: @comment%>
    <%= form_for [@post, @comment] do |f|%>

    <div class="control-group">
      <%= f.label :body, 'Leave a comment'%>
      <%= f.text_area :body, rows: 3, class: 'span4'%>
    </div>
      <br/>

      <%= f.submit "Create Comment", class:"btn btn-primary"%>
    <%end%>
  <%else%>
    <div>
      <%= link_to "Sign in to leave a comment", login_path%>
    </div>
  <%end%>
</div>
<hr/>

<div class="well">
  <% @post.comments.each do |comment|%>
    <%= render 'comments', comment: comment%>
  <%end%>
</div>

app/views/shared/_content_title.html.erb
<p class="lead">
  <%= title%>
  <hr/>
</p>

app/views/shared/_errors.html.erb
<% if object.errors.any?%>
<div class="alert alert-error">
  <h5>Error:</h5>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <%end%>
  </ul>
</div>
<%end%>

app/views/users/_form.html.erb
<%= render 'shared/errors', object: @user%>
<div class="well">
  <%= form_for @user do |u|%>

    <p class="control-group">
      <%= u.label :username %>
      <%= u.text_field :username %>
    </p>

    <p class="control-group">
      <%= u.label :password %>
      <%= u.password_field :password %>
    </p>

    <%= u.submit(@user.new_record? ? "Register" : "Update Profile")%>

  <%end%>
</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: "Edit Profile"%>

<%= render 'form' %>

app/views/users/new.html.erb
<h4>Register a user!</h4>

<%= render 'form'%>

app/views/users/show.html.erb
<div class="well">
  <strong>Profile Details</strong>
  <hr/>
  <p>
    Username :  <%= @user.username%>
  </p>
</div>

<div>Activity:
  <ul class="nav nav-tabs">
    <li class="<%= 'active' if params[:tab] == 'posts' %>">
      <%= link_to "Posts (#{@user.posts.count})", user_path(@user, tab: 'posts')%>
    </li>
    <li class="<%= 'active' if params[:tab] == 'comments' %>">
      <%= link_to "Comments (#{@user.comments.count})", user_path(@user, tab: 'comments')%>
    </li>
  </ul>
</div>

<% if params[:tab] == 'posts'%>
  <% @user.posts.each do |post|%>
    <%= render 'posts/post', post: post %>
  <%end%>
<%elsif params[:tab] == 'comments'%>
  <div class="well">
    <% @user.comments.each do |comment|%>
      <%= render 'posts/comments', comment: comment , show_title: true%>
    <%end%>
  </div>
<%end%>